# Generated by Django 5.2.3 on 2025-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='desconto_aplicado',
            field=models.BooleanField(default=False),
        ),
    ]
