# Generated by Django 5.2.3 on 2025-07-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_itemvenda_desconto_aplicado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvenda',
            options={'ordering': ['produto']},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['cliente']},
        ),
    ]
