# Generated by Django 5.2.3 on 2025-07-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
