# Generated by Django 5.2.3 on 2025-07-11 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Informe um CPF ou CNPJ apenas com números.', regex='^\\d{11}$|^\\d{14}$')], verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
