# Generated by Django 5.2.3 on 2025-07-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF ou CNPJ'),
        ),
    ]
